# Generated by Django 4.1.3 on 2022-12-03 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=64, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=14, unique=True, verbose_name='Телефон')),
                ('firstname', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('teacher', 'Учитель'), ('parent', 'Родитель'), ('student', 'Ученик')], default='student', max_length=12, verbose_name='Роль')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Модератор?')),
                ('is_active', models.BooleanField(default=True, help_text='Включено, когда аккаунт не в бане', verbose_name='Активный?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Администратор')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее посещение')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'auth__user',
            },
        ),
    ]
