# Generated by Django 4.1.3 on 2022-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник?'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('organization', 'Организация'), ('staff', 'Сотрудник')], default='client', max_length=12, verbose_name='Роль'),
        ),
    ]
