# Generated by Django 4.1.3 on 2022-12-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_usermodel_last_visit_usermodel_patronymic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='login',
            new_name='username',
        ),
    ]
