# Generated by Django 4.1.3 on 2022-12-03 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('birthday_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
                'db_table': 'account__child',
            },
        ),
        migrations.CreateModel(
            name='PassportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, verbose_name='Серия')),
                ('number', models.CharField(max_length=6, verbose_name='Номер')),
                ('date_of_issue', models.DateTimeField(verbose_name='Дата выдачи')),
                ('whom_issued', models.TextField(null=True, verbose_name='Кем выдан')),
                ('type', models.CharField(choices=[('russian', 'Российский'), ('foreign', 'Зарубежный')], default='russian', max_length=16, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
                'db_table': 'account__passport',
            },
        ),
        migrations.CreateModel(
            name='RepresentativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('STATUS', models.CharField(choices=[('parent', 'Родитель'), ('representative', 'Законный представитель')], default='parent', max_length=32, verbose_name='Статус')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.addressmodel', verbose_name='Адрес')),
                ('children', models.ManyToManyField(blank=True, to='account.childmodel', verbose_name='Дети')),
                ('passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.passportmodel', verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'Представитель',
                'verbose_name_plural': 'Представители',
                'db_table': 'account__representative',
            },
        ),
    ]
