# Generated by Django 4.1.3 on 2022-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='snils',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='passportmodel',
            name='duration',
            field=models.DateField(null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='representativemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон'),
        ),
    ]
