# Generated by Django 4.1.3 on 2022-12-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_addressmodel_area_addressmodel_country_and_more'),
        ('account', '0003_representativemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representativemodel',
            name='address',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.addressmodel', verbose_name='Адрес'),
        ),
    ]
