# Generated by Django 4.1.3 on 2022-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_childmodel_birthday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportmodel',
            name='date_of_issue',
            field=models.DateTimeField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='passportmodel',
            name='duration',
            field=models.DateTimeField(null=True, verbose_name='Срок действия'),
        ),
    ]
