# Generated by Django 4.1.3 on 2022-12-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_addressmodel_area_addressmodel_country_and_more'),
        ('account', '0006_alter_passportmodel_date_of_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmodel',
            name='address',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='registration_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_address', to='address.addressmodel', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='residence_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_address', to='address.addressmodel', verbose_name='Адрес'),
        ),
    ]
