# Generated by Django 4.1.3 on 2022-12-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_addressmodel_area_addressmodel_country_and_more'),
        ('account', '0007_remove_childmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='registration_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_address', to='address.addressmodel', verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='residence_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_address', to='address.addressmodel', verbose_name='Адрес проживания'),
        ),
    ]
