# Generated by Django 4.1.3 on 2022-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_birthcertificatemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childmodel",
            name="birthday_date",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
    ]
