# Generated by Django 4.1.3 on 2022-12-03 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_addressmodel_area_addressmodel_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampOrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='Описание')),
                ('camping_type', models.CharField(choices=[('stationary', 'Стационарный лагерь'), ('army', 'Палаточный военно-патриотический лагерь'), ('tourist', 'Палаточный туристический лагерь')], max_length=64, verbose_name='Тип лагеря')),
                ('day_begin', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало трудового дня')),
                ('day_end', models.TimeField(default=datetime.time(23, 59, 59, 999999), verbose_name='Конец трудового дня')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона для справок')),
                ('housing_quantity', models.IntegerField(default=0, verbose_name='Количество корпусов')),
                ('area', models.IntegerField(default=0, verbose_name='Площадь территории')),
                ('meal_type', models.CharField(choices=[('portioned', 'Порционное'), ('buffet', 'Шведский стол')], max_length=24, verbose_name='Тип питания')),
                ('having_sports_objects', models.BooleanField(default=False, verbose_name='Наличие спортивных объектов')),
                ('having_relaxing_objects', models.BooleanField(default=False, verbose_name='Наличие досуговых объектов')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.addressmodel', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Лагерь',
                'verbose_name_plural': 'Лагеря',
                'db_table': 'camp__organization',
            },
        ),
        migrations.CreateModel(
            name='СampEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название лагерной смены')),
                ('camping_type', models.CharField(choices=[('stationary', 'Стационарный лагерь'), ('army', 'Палаточный военно-патриотический лагерь'), ('tourist', 'Палаточный туристический лагерь')], max_length=64, verbose_name='Тип лагерной смены')),
                ('date_begin', models.DateField(verbose_name='День начала лагерной смены')),
                ('date_end', models.DateField(verbose_name='День окончания лагерной смены')),
                ('season', models.CharField(choices=[('spring', 'Весенние заезды'), ('summer', 'Летние заезды'), ('fall', 'Осенние заезды'), ('winter', 'Зимние заезды')], max_length=32, verbose_name='Лагерный сезон')),
                ('having_rest_certificate', models.BooleanField(default=False, verbose_name='Наличие сертификата на отдых')),
                ('camp_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_events', to='camp.camporganizationmodel')),
            ],
            options={
                'verbose_name': 'Лагерная смена',
                'verbose_name_plural': 'Лагерные смены',
                'db_table': 'camp__event',
            },
        ),
    ]
