# Generated by Django 4.1.3 on 2022-12-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
        ("camp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="СampEventModel",
            new_name="CampEventModel",
        ),
    ]
