# Generated by Django 4.1.3 on 2022-12-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0002_rename_сampeventmodel_campeventmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campeventmodel",
            name="camp_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camp_events",
                to="camp.camporganizationmodel",
                verbose_name="Лагерь-организатор",
            ),
        ),
        migrations.AlterField(
            model_name="campeventmodel",
            name="camping_type",
            field=models.CharField(
                choices=[
                    ("stationary", "Стационарный лагерь"),
                    ("army", "Палаточный военно-патриотический лагерь"),
                    ("tourist", "Палаточный туристический лагерь"),
                ],
                max_length=64,
                verbose_name="Тип смены",
            ),
        ),
        migrations.AlterField(
            model_name="campeventmodel",
            name="date_begin",
            field=models.DateField(verbose_name="День начала"),
        ),
        migrations.AlterField(
            model_name="campeventmodel",
            name="date_end",
            field=models.DateField(verbose_name="День окончания"),
        ),
        migrations.AlterField(
            model_name="campeventmodel",
            name="title",
            field=models.CharField(max_length=64, verbose_name="Название"),
        ),
    ]
