# Generated by Django 4.1.3 on 2022-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_camporganizationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeventmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
