# Generated by Django 4.1.3 on 2022-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_campeventmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeventmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
