# Generated by Django 4.1.3 on 2022-12-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_alter_childmodel_citizenship_and_more'),
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.сampeventmodel', verbose_name='Лагерная смена')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.childmodel', verbose_name='Ребенок')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.representativemodel', verbose_name='Представитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'request__request',
            },
        ),
    ]
