# Generated by Django 4.1.3 on 2022-12-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Россия', max_length=128, verbose_name='Страна')),
                ('region', models.CharField(max_length=128, null=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'address__region',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=128, verbose_name='Район')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.regionmodel', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'address__city',
            },
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(verbose_name='Улица')),
                ('number', models.TextField(verbose_name='Номер дома')),
                ('corpus', models.TextField(blank=True, null=True, verbose_name='Корпус')),
                ('flat_number', models.TextField(verbose_name='Номер квартиры')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.citymodel', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address__address',
            },
        ),
    ]
