# Generated by Django 4.1.3 on 2022-12-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='area',
            field=models.CharField(max_length=128, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='country',
            field=models.CharField(default='Россия', max_length=128, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='region',
            field=models.CharField(max_length=128, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(max_length=128, null=True, verbose_name='Город'),
        ),
    ]
