# Generated by Django 4.1.3 on 2022-12-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_addressmodel_area_addressmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='area',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='flat_number',
            field=models.TextField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
    ]
